package certificados.service.exception;

public class AlunoNaoEncontradoException extends RuntimeException {

    public AlunoNaoEncontradoException() {
        super("Aluno n√£o foi encontrado");
    }
}
